name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/setup-pnpm@v1

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test

      - name: Run Semantic Release
        run: npx semantic-release
